pr:
  branches:
    include:
      - feat/cd
trigger:
  branches:
    include:
      - feat/cd
  tags:
    include:
      - "*"

variables:
  - name: buildId
    value: $(Build.BuildId)

  - name: vmImage
    value: ubuntu-latest

  - name: k8sNamespace
    value: coracoesdalila

  - name: connectionType
    value: Kubernetes Service Connection

  - name: acrServiceConnection
    value: "docker-registry"

  - name: aksServiceConnection
    value: "AKS-DBSERVER"

  - name: dockerRepository
    value: "coracoesdalila/frontend"

  - name: isTag
    value: $[startsWith(variables['Build.SourceBranch'],'refs/tags/')]

  - name: branchName
    value: $(Build.SourceBranchName)

  - name: acrUrl
    value: "dbserverregistry.azurecr.io/coracoesdalila/frontend"

  - name: isMergePRREMOVE
    value: eq(variables['Build.Reason'], 'PullRequest')
  

pool:
  vmImage: $(vmImage)

stages:
  - stage: CI
    jobs:
      - job: CI
        displayName: Run tests, build and push image to ACR
        steps: 
          - task: Npm@1
            displayName: "Installing dependencies"
            inputs:
              workingDir: ./
              command: "install"
          # - task: Npm@1
          #   displayName: "Running tests"
          #   inputs:
          #     command: custom
          #     workingDir: ./
          #     customCommand: "run test:noInterface"
          - task: Npm@1
            condition: or(eq(variables['isTag'], 'true'), ne(variables['Build.Reason'], 'PullRequest'))
            displayName: "Building project"
            inputs:
              command: custom
              workingDir: ./
              ${{ if eq(variables['isTag'], true) }}:
                customCommand: "run build:prd"
              ${{ else }}:
                customCommand: "run build:staging"
              
          - task: Docker@2
            displayName: Building docker image and pushing to ACR
            condition: and(succeeded(), or(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['isTag'], 'true')))
            inputs:
              containerRegistry: $(acrServiceConnection)
              repository: $(dockerRepository)
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), ne(variables['isTag'], ''))}}:
                tags: |
                  $(buildId)
                  latest
              ${{ if eq(variables['isTag'], 'true') }}:
                tags: $(branchName)
              

  - stage: DeployToDevelopment
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['isTag'], 'true'))
    variables:
      - name: enviroment
        value: "dev"
      - name: ingress_domain
        value: "coracoesdalila-dev"
    jobs:
      - job: ApplyManifests
        displayName: Applying kubernetes manifests
        steps:
          - task: ShellScript@2
            displayName: Changing yaml's variables
            inputs:
              scriptPath: "./kubernetes/change_variables.sh"
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              kubernetesServiceConnection: $(aksServiceConnection)
              manifests: |
                ./kubernetes/deployment.yaml
                ./kubernetes/service.yaml
              containers: |
                $(acrUrl):latest
          - task: Kubernetes@1
            displayName: Apply Ingress
            inputs:
              connectionType: $(connectionType)
              kubernetesServiceEndpoint: $(aksServiceConnection)
              namespace: $(k8sNamespace)
              command: "apply"
              useConfigurationFile: true
              configuration: "./kubernetes/ingress.yaml"
              outputFormat: none
          - task: Kubernetes@1
            displayName: Restart service
            inputs:
              connectionType: $(connectionType)
              kubernetesServiceEndpoint: $(aksServiceConnection)
              namespace: $(k8sNamespace)
              command: "rollout"
              arguments: "restart deploy coracoesdalila-app-dev"

  - stage: DeployToProduction
    condition: eq(variables['isTag'], 'true')
    variables:
      - name: enviroment
        value: "prd"
      - name: ingress_domain
        value: "coracoesdalila"
    jobs:
      - job: ApplyManifests
        displayName: Applying kubernetes manifests
        steps:
          - task: ShellScript@2
            displayName: Changing yaml's variables
            inputs:
              scriptPath: "./kubernetes/change_variables.sh"
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              kubernetesServiceConnection: $(aksServiceConnection)
              manifests: |
                ./kubernetes/deployment.yaml
                ./kubernetes/service.yaml
              containers: |
                $(acrUrl):$(branchName)
          - task: Kubernetes@1
            displayName: Apply Ingress
            inputs:
              connectionType: $(connectionType)
              kubernetesServiceEndpoint: $(aksServiceConnection)
              namespace: $(k8sNamespace)
              command: "apply"
              useConfigurationFile: true
              configuration: "./kubernetes/ingress.yaml"
              outputFormat: none
          - task: Kubernetes@1
            displayName: Restart service
            inputs:
              connectionType: $(connectionType)
              kubernetesServiceEndpoint: $(aksServiceConnection)
              namespace: $(k8sNamespace)
              command: "rollout"
              arguments: "restart deploy coracoesdalila-app-prd"
