apiVersion: apps/v1
kind: Deployment
metadata:
  name: coracoesdalila-app-${ENV}
  namespace: coracoesdalila
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coracoesdalila-app-${ENV}
  template:
    metadata:
      labels:
        app: coracoesdalila-app-${ENV}
    spec:
      containers:
        - name: coracoesdalila-app-${ENV}
          image: "dbserverregistry.azurecr.io/coracoesdalila/frontend"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
