apiVersion: v1
kind: Service
metadata:
  name: coracoesdalila-app-service-${env}
  namespace: coracoesdalila
  labels:
    app: coracoesdalila-app-${env}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: coracoesdalila-app-${env}
